module ID3
  module V2
    class FrameLookup
      type frame_class = singleton(Frame)

      type frame_attributes = Hash[Symbol, untyped]

      FRAME_TYPES: Hash[Symbol, frame_attributes]

      DEFAULT_FRAME_CLASS: frame_class

      class FrameType
        attr_reader name: Symbol
        attr_reader frame_class: frame_class

        def initialize: (**untyped) -> void
      end

      def self.find: (Symbol) -> FrameType
    end
  end
end
