module ID3
  module V2
    class Tag < StreamSection
      attr_reader header: TagHeader
      attr_reader frames: Array[Frame]

      def initialize: (IO) -> void

      def self.from_file: (String) -> Tag

      private

      def end_of_tag?: -> bool
    end
  end
end
