module AudioTag
  module ID3
    module V2
      class TagHeader < Header
        STRUCTURE: Array[Symbol]

        IDENTIFIER: String

        INVALID_FLAG_MASK:   Integer
        EXPERIMENTAL_MASK:   Integer
        EXTENDED_MASK:       Integer
        UNSYNCHRONISED_MASK: Integer

        def experimental?: -> bool

        def extended?: -> bool

        def unsynchronised?: -> bool

        attr_reader tag_size: Integer

        attr_reader total_size: Integer

        private

        attr_reader identifier: String

        attr_reader flags: Integer

        def validate_identifier!: -> void

        def validate_flags!: -> void
      end
    end
  end
end
