module ID3
  class Header < StreamSection
    attr_reader bytes: bytes

    def bytes_for: (Symbol) -> bytes

    private

    UNEXTENDED_SIZE: Integer

    def structure: -> Array[Symbol]

    def structure_defined?: -> bool
  end
end
