module AudioTag
  module ID3
    module V2
      module Frames
        class PictureFrame < Frame
          ENCODINGS: Array[Symbol]

          TYPES: Array[Symbol]

          def data: -> Hash[Symbol, untyped]

          private

          attr_reader mime: String
          attr_reader description: String

          @encoding: Integer
          @type: Integer

          def encoding: -> Symbol

          def type: -> Symbol
        end
      end
    end
  end
end
